name: CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: create env file
        run: |
          touch .env
          echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env


      - name: Run code coverage test
        run: npm test -- --coverage

      - name: Remove .env file
        run: rm -f .env

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stinbank-express:latest ./backend

      - name: Push the Docker image to the repository
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stinbank-express:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH into vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker stop stinbank-express
            docker rm stinbank-express
            docker pull ${{ secrets.DOCKER_USERNAME }}/stinbank-express:latest
            docker run -d --name stinbank-express -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/stinbank-express:latest
            
