name: CI/CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: create env file
        run: |
          touch .env
          echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env


      - name: Run code coverage test
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Remove .env file
        run: rm -f .env
